[package]
name = "friz"
version = "0.0.1"
authors = ["Ryan Levick <ryan.levick@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
hyper = "*"
rustc-serialize = "*"
url = "*"
oauthcli = "*"
serde_derive = "*"
serde = "*"
serde_json = "*"
